Create exception class for default credentials not found
googleapis/google-auth-library-ruby pull request #380
Opened 2022-04-08 13:35 UTC by bouk

Part of https://github.com/googleapis/google-auth-library-ruby/issues/304

Potentially we should make `Google::Auth::Error` a subclass of RuntimeError so we don't break backwards compatibility?

2022-04-18 19:03 UTC, viacheslav-rostovtsev requested changes

2022-04-18 19:03 UTC, viacheslav-rostovtsev commented on lib/googleauth/error.rb
> +    class DefaultCredentialsNotFoundError < Error
Missing docs for the new classes.

2022-05-24 06:13 UTC, NivedhaSenthil commented
@bouk gentle follow up to see if you are still looking at this ?

2022-08-25 05:50 UTC, bajajneha27 commented
Hi @bouk 
I'm closing the PR due to inactivity. Please feel free to reopen it if you still want to continue working on it.

2022-08-25 05:50 UTC, closed without merging